baseURL: "https://gohanko.github.io/pages/"
title: "Yii Kuo Chong"
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTxt: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts"]

minify:
    disableXML: true
    minifyOutput: true

pagination:
  disableAliases: false
  pagerSize: 5

languages:
  en:
    languageName: "English"
    weight: 1
    title: "Welcome to my space!"
    menu:
      main:
        - name: Archive
          url: /archives/
          weight: 5
        - name: Tags
          url: /tags/
          weight: 10
        - identifier: About
          name: About
          url: /about/
          weight: 30

params:
  env: production
  description: "thoughts on web development, cybersecurity and life"
  author: Yii Kuo Chong / 俞國忠
  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  homeInfoParams:
    Title: "Welcome to my home page!"
    Content: |
      I"m Yii Kuo Chong / 俞國忠 (call me Brandon), and this is a website where I publish my thoughts and knowledge on web and android development, + some other random tech related topics like reverse engineering.
  socialIcons:
    - name: github
      title: View Source on Github
      url: "https://github.com/gohanko"
    - name: linkedin
      title: Find me on LinkedIn
      url: "https://www.linkedin.com/in/gohanko/"
    - name: telegram
      title: Message me on Telegram
      url: "https://t.me/emergencyfood"
  assets:
    disableHLJS: true
    disableFingerprinting: true
  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page
  markup:
    goldmark:
      renderer:
        unsafe: true
    highlight:
      noClasses: false
  services:
    instagram:
      disableInlineCSS: true
    x:
      disableInlineCSS: true